import type { Metadata } from 'next';
import { Dosis } from 'next/font/google';
import './globals.css';
import StyledComponentRegistry from './lib/registry';
import { ApolloWithSessionWrapper } from './utils/ApolloWithSessionWrapper';

const dosis = Dosis({ subsets: ['latin'], display: 'swap' });
export const metadata: Metadata = {
    title: 'Restaurant App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <StyledComponentRegistry>
                <ApolloWithSessionWrapper>
                    <body className={dosis.className}>{children}</body>
                </ApolloWithSessionWrapper>
            </StyledComponentRegistry>
        </html>
    );
}
